version: "3.4"
  services:
    main:
      #image: ubuntu:16.04
      build:
        context: ./
        dockerfile: Dockerfile
        labels:
          - "ntc.description=File/Terminal server to access container"
          - "ntc.builds.amss=apps"
      command: /bin/sh -c "sudo sysctl fs.inotify.max_user_watches=524288 && sudo sysctl -p && /usr/local/bin/jupyter notebook --ip=0.0.0.0 --port=8888"
      ports:
        - "9999:8888"
      privileged: true
      environment:
      volumes:
        - '/opt/cross:/opt/cross'
        - '/var/shared:/var/shared'